project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "static_dashboard/"
    - "!shiny_dashboard/"  # Excludes shiny_dashboard directory

website:
  title: "Demo Dashboard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dashboard"
        href: static_dashboard/demo_dashboard.qmd
  
format:
  html:
    theme: cosmo
    toc: true  